version: "3.8"

services:
  frontend:
    image: nginx-frontend
    build:
      context: ./frontend-v2
    ports:
      - "80:80"
    networks:
      - frontend
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

networks:
  frontend:
