version: "3.8"

services:
  frontend:
    image: nginx-frontend
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - frontend
    extra_hosts:
      - "host.docker.internal.host-gateway"

networks:
  frontend:
