server_tokens off;
client_max_body_size 500M;

server {
  listen 80 default_server;
  listen [::]:80 default_server;
  server_name _;

  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  include /etc/nginx/snippets/common-ssl.conf;
  server_name home.box www.home.box;
  root /usr/share/nginx/html;
  try_files $uri /index.html;
}

server {
  listen 443 ssl;
  include /etc/nginx/snippets/common-ssl.conf;
  server_name photoprism.home.box www.photoprism.home.box;

  location / {
    include /etc/nginx/snippets/common-proxy.conf;
    proxy_pass http://host.docker.internal:2342;
  }
}

server {
  listen 443 ssl;
  include /etc/nginx/snippets/common-ssl.conf;
  server_name openbooks.home.box www.openbooks.home.box;

  location / {
    include /etc/nginx/snippets/common-proxy.conf;
    proxy_pass http://host.docker.internal:8081;
  }
}

server {
  listen 443 ssl;
  include /etc/nginx/snippets/common-ssl.conf;
  server_name plex.home.box www.plex.home.box;

  location / {
    include /etc/nginx/snippets/common-proxy.conf;
    proxy_pass http://host.docker.internal:32400;
  }
}

server {
  listen 443 ssl;
  include /etc/nginx/snippets/common-ssl.conf;
  server_name jellyfin.home.box www.jellyfin.home.box;

  location / {
    include /etc/nginx/snippets/common-proxy.conf;
    proxy_pass http://host.docker.internal:8096;
  }
}

server {
  listen 443 ssl;
  include /etc/nginx/snippets/common-ssl.conf;
  server_name jellyswarrm.home.box www.jellyswarrm.home.box;

  location / {
    include /etc/nginx/snippets/common-proxy.conf;
    proxy_pass http://host.docker.internal:3000;
  }
}
